# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classList',
            fields=[
                ('class1', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='classSection',
            fields=[
                ('section', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('classSec', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classList')),
            ],
        ),
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
    ]
