# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classSection',
            fields=[
                ('classSec', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class1', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.BinaryField(max_length=512)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('profileText', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userAccount'),
        ),
    ]
