# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class1',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='classList',
        ),
    ]
