# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='classSec',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
