# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161127_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
    ]
