# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161127_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday',
        ),
    ]
