# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161129_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday',
        ),
    ]
